CREATE TABLE IF NOT EXISTS AgentMemory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  memory_key TEXT UNIQUE NOT NULL,
  memory_value TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
